### PR TITLE
Fix run_partially

### PR DESCRIPTION
**Pull request by backus**
- Now will only run files that have changed
- Bump to 0.0.4

---

I haven't thoroughly tested this or anything but it is doing what I want.

### CODE REVIEW

**Comment by backus** [comment]
Actually hold off on merging until I get another commit up later so that this doesn't break run_all

**Comment by backus** [comment]
Alright should be good to go if you would like to merge @mdeering

**Comment by mdeering** [comment]
Master repository for guard-yardstick is here https://github.com/X0nic/guard-yardstick I have the same pull request ready to go over there: https://github.com/X0nic/guard-yardstick/pull/2

I just got permissions on that repository and on rubygems.org so I will be releasing it this week. Give that pull request a watch.

**Comment by mdeering** [comment]
@backus Just released 0.1 to rubygems.org

**Pull request closed without merging**
